### PR TITLE
Kb/fix/error handling

### LINKED ISSUE #32: Refactor - Error handling on About and Contact Pages
**Describe the bug / point of concern**
> Double check our error handling on About and Contact Pages, "Too Rowdy" error persists on About and Contact Pages when api call is rejected.

### PR DESCRIPTION
**Pull request by kristenmb**
#### Any relevant tickets?
#32

### CODE REVIEW

File: cypress/integration/details_spec.js [hunk 1]
```diff
@@ -26,13 +18,20 @@ describe('Money Plane Details view', () => {
...
 
     cy.visit(baseUrl)
   });
 
+  it ('Should show a loading status while fetching movie details', () => {
+    cy
+      .get('.loading').should('contain', 'Loading')
+      .should('be.visible')
+  });
+
```
Comment (dietza) [inline cypress/integration/details_spec.js:34]: Helpful - thanks for adding this and showing me how to incorporate that delay (pretty straight-forward!)

File: cypress/integration/details_spec.js [hunk 2]
```diff
@@ -91,3 +95,18 @@ describe('Details view error handling - Money Plane', () => {
...
+  it ('Shows an error for a 500 status code response', () => {
+    cy.intercept('GET', 'https://rancid-tomatillos.herokuapp.com/api/v2/movies/694919', {
+      statusCode: 500,
+    })
+
+    cy.visit(baseUrl)
+      .get('.error-message').should('contain', 'These taters got too rowdy - check back later!')
+  })
+
+});
```
Comment (dietza) [inline cypress/integration/details_spec.js:112]: Cool, I don't know that we needed any different error message to display here, but like this additional check on the specific 500 status code.

File: src/Components/App/App.js [hunk 3]
```diff
@@ -52,23 +52,24 @@ class App extends Component {
         <Header filterMoviesDisplay={ this.filterMoviesDisplay }/>
       
         {this.state.isLoading && !this.state.error &&
-        <h2>Loading...</h2>}
+        <h2 className="loading">Loading...</h2>}
```
Comment (dietza) [inline src/Components/App/App.js:55]: nice, thanks for catching that!

File: src/Components/DetailsDisplay/DetailsDisplay.js [hunk 4]
```diff
@@ -24,24 +25,35 @@ const DetailsDisplay = ({ movieToDisplay, trailersToDisplay }) => {
...
+        </p>}
+        {releaseYear && runtime === 0 && <p className='details__movie-release'>
+          {`${releaseYear}`}
+        </p>}
+        {!releaseYear && runtime !== 0 && <p className='details__movie-release'>
+          {`${runtime} mins`}
+        </p>}
+        
+        {movieToDisplay.overview && <p className='details__movie-overview'> {movieToDisplay.overview} </p>}
+        {!movieToDisplay.overview && <p>No synopsis provided</p>}
```
Comment (dietza) [inline src/Components/DetailsDisplay/DetailsDisplay.js:40]: Appreciate how you put the conditional rendering together for this - glad you noticed the sparse info provided for that movie!

**Review by dietza — APPROVED** [review]
So glad you caught the pieces we had missed checking for here! 
And thanks for showing me what you found you found to handle them. 🙏🏻
