### PR TITLE
Ad/refactor/accessibility

### LINKED ISSUE #33: Refactor- Accessibility
**Describe the bug / point of concern**
> Per lighthouse Audit: 
>   - discernible names on a tags
>   - label on form elements

### PR DESCRIPTION
**Pull request by dietza**
Reaches 100% on Lighthouse audits for each page view.

Lines 22 & 32 in Contact.js
Line 17 in Footer.css
Line 15 in MovieCard.js
Lines 22 & 28 in SearchBar.js

In the dev tools, run Lighthouse to view passing audits.

### CODE REVIEW

File: src/Components/About/About.js [hunk 1]
```diff
@@ -17,7 +17,7 @@ const About = () => {
       <div className="img-wrap">
         <img 
           src={tot} 
-          alt="BEAUTIFUL CAT"
+          alt="a rowdy, long-haired, orange and white cat named 'Tater Tot' lies out-stretched on his back, looking at the camera"
```
Comment (kristenmb) [inline src/Components/About/About.js:20]: love this description so much

File: src/Components/Contact/Contact.js [hunk 2]
```diff
@@ -19,7 +19,7 @@ const Contact = () => {
         <section className="contacts">
           <article className="contact-info AD">
             <div className="prof-pic-wrap">
-            <img src={AD} alt="BEAUTIFUL ALLISON" className="prof-pic"/>
+            <img src={AD} alt="a woman wearing a windbreaker and solar glasses stares out into the sky" className="prof-pic"/>
```
Comment (kristenmb) [inline src/Components/Contact/Contact.js:22]: also love this

File: src/Components/Contact/Contact.js [hunk 3]
```diff
@@ -29,7 +29,7 @@ const Contact = () => {
           </article>
           <article className="contact-info KB">
             <div className="prof-pic-wrap">
-              <img src={KB} alt="BEAUTIFUL KRISTEN" className="prof-pic"/>
+              <img src={KB} alt="a woman with blue hair, wearing a scarf and denim jacket, smiles for an approachable portrait" className="prof-pic"/>
```
Comment (kristenmb) [inline src/Components/Contact/Contact.js:32]: 'approachable portrait' is such a nice touch

File: src/Components/MovieCard/MovieCard.js [hunk 4]
```diff
@@ -12,7 +12,7 @@ const MovieCard = ({ info, showSelection }) => {
   }
 
   return (
-    <article className='movie-card' onClick={getID} id={info.id}>
+    <article className='movie-card' onClick={getID} id={info.id} name={`${info.title}-card`} aria-label={`${info.title}-card`}>
```
Comment (kristenmb) [inline src/Components/MovieCard/MovieCard.js:15]: Such a clean way to add a label - love it

**Review by kristenmb — APPROVED** [review]
These changes look great! Thanks Allison
